# Generated by Django 5.2.3 on 2025-06-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_info_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Masculino"),
                    ("F", "Femenino"),
                    ("O", "Outro"),
                    ("N", "Prefiro não informar"),
                ],
                default="U",
                max_length=2,
            ),
        ),
    ]
